apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-app
spec:
  selector:
    matchLabels:
      app: client-app
  replicas: 3    
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
      - name: client-app-container
        image:  image-registry.openshift-image-registry.svc:5000/client-service/client-service-image:1.0
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: client-app-service
spec:
  selector:
    app: client-app
  ports:
  - protocol: TCP
    port: 9080

---
apiVersion: v1
kind: Route
metadata:
  name: client-service-route
spec:
  to:
    kind: Service
    name: client-app-service
---