apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-app
spec:
  selector:
    matchLabels:
      app: client-app
  replicas: 3    
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
      - name: client-app-container
        image:  client-service:1.0
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: client-app-service
spec:
  type: NodePort
  selector:
    app: client-app
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000